---

- name: copy PHP opcache include config
  template:
    src: php/apache2/conf.d/nextcloud-opcache.ini
    dest: "/etc/php{{ '5' if ansible_distribution_major_version|int <= 8 else '/7.0' }}/apache2/conf.d/nextcloud-opcache.ini"
    owner: root
    group: root
    mode: 0644
  notify: test and restart apache2

- name: Check which PHP variables are set in .htaccess
  command: 'grep -Eq "php_value\s+{{ item.key }}" {{ nextcloud_webroot }}/.htaccess'
  with_dict: "{{ nextcloud_php_settings|d({}) }}"
  register: nextcloud_reg_htaccess_vars
  check_mode: False
  failed_when: False
  changed_when: False

- name: Replace existing PHP variables in .htaccess
  replace:
    dest: "{{ nextcloud_webroot }}/.htaccess"
    regexp: '^(\s*)php_value\s+{{ item.key }}.*$'
    replace: '\1php_value {{ item.key }} {{ item.value }}'
  with_items: "{{ nextcloud_reg_htaccess_vars|json_query(query) }}"
  vars:
    query: "results[?rc == `0`].item"

- name: Add new PHP values to .htaccess
  replace:
    dest: "{{ nextcloud_webroot }}/.htaccess"
    regexp: '^(<IfModule mod_php.*)$'
    replace: '\1\n  php_value {{ item.key }} {{ item.value }}'
  with_items: "{{ nextcloud_reg_htaccess_vars|json_query(query) }}"
  vars:
    query: "results[?rc == `1`].item"

- name: Set PHP variables in .user.ini
  lineinfile:
    dest: "{{ nextcloud_webroot }}/.user.ini"
    regexp: '^{{ item.key }}=.*$'
    line: '{{ item.key }}={{ item.value }}'
  with_dict: "{{ nextcloud_php_settings|d({}) }}"
