- name: install Nextcloud dependencies
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ nextcloud_dependencies }}"
  tags:
    - role:nextcloud:install
    - role:nextcloud:upgrade

- include: nextcloud-vhost.yml
  loop_control:
    loop_var: vhost_item
  with_flattened: "{{ apache2_vhosts }}"
  when: apache2_vhosts|d()

- include: nextcloud-vhost.yml
  vars:
    - vhost_item: {}
  when: not apache2_vhosts|d()

- include: nextcloud-apache-php.yml
  when: nextcloud_apache_php|d()
  tags:
    - role:nextcloud:apache
