- name: install Nextcloud dependencies
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ nextcloud_dependencies }}"
  tags:
    - role:nextcloud:install
    - role:nextcloud:upgrade
  when: "'nextcloud' in apache2_vhosts|d()|json_query('[*].[webapps][][]')"

- include: nextcloud-vhost.yml
  loop_control:
    loop_var: vhost_item
  with_flattened: "{{ apache2_vhosts }}"
  when: "'nextcloud' in apache2_vhosts|d()|json_query('[*].[webapps][][]')"
